# using Tar, Inflate, SHA
# cd("C:\\Users\\pi96doc\\Documents\\Programming\\Java\\View5D")
# V = 2; VV = 5; VVV = 5; Suffix = "-SNAPSHOT";
# VJ = 0; VVJ=5; VVVJ=3;
# include("src\\get_artifact_info.jl")
# replace the code below with the printout
#
# remember to change the version number in the View5D.jl Project.toml file!
# Note that the Julia Version does not agree to the version of the Java View5D.
# for a full release: update the version number in Project.toml and comment "@JuliaRegistrator register"
# For reference the lines to generate the hashes below
# println("git-tree-sha1 = \"", Tar.tree_hash(IOBuffer(inflate_gzip(filename))),"\"")
# println("sha256 = \"", bytes2hex(open(sha256, filename)), "\"")
# https://github.com/bionanoimaging/View5D/releases/download/View5D_v2.5.5/View5D_-2.5.5-SNAPSHOT-jar.tar.gz

[View5D-jar]
git-tree-sha1 = "f9161b15ca767c30153fe71f62eac9810c7e0290"
lazy = true

    [[View5D-jar.download]]
    url = "https://github.com/bionanoimaging/View5D/releases/download/View5D_v2.5.5/View5D_-2.5.5-SNAPSHOT-jar.tar.gz"
    sha256 = "9ac53a78e0c44294cb5140ef7d400bbe7890036d3f23547d85fbd70deb96e1b0"
