# using Tar, Inflate, SHA
# cd("C:\\Users\\pi96doc\\Documents\\Programming\\Java\\View5D")
# filename = "View5D_v2.3.2-jar.tar.gz"
# println("git-tree-sha1 = \"", Tar.tree_hash(IOBuffer(inflate_gzip(filename))),"\"")
# println("sha256 = \"", bytes2hex(open(sha256, filename)), "\"")
# https://github.com/RainerHeintzmann/View5D/releases/download/View5D_v2.3.2/View5D_v2.3.2-jar.tar.gz
# or easier: include("src\\GetArtifactInfo.jl")

[View5D-jar]
git-tree-sha1 = "073dda96b19880514fae1cbbe537146aed394885"
lazy = true

    [[View5D-jar.download]]
    url = "https://github.com/RainerHeintzmann/View5D/releases/download/View5D_v2.3.2/View5D_v2.3.2-jar.tar.gz"
    sha256 = "aca372bf2abb729e9ada0a8c46126e459cffa71be01dccb4c33d9ced6157de13"
