# using Tar, Inflate, SHA

# filename = "View5D_-2.3.1.jar"
# println("sha256: ", bytes2hex(open(sha256, filename)))
# println("git-tree-sha1: ", Tar.tree_hash(IOBuffer(inflate_gzip(filename))))

# https://github.com/fiji/View5D/releases/download/2.3.1-jar/View5D_-2.3.1.jar.tar.gz

[View5D-jar]
git-tree-sha1 = "3f13f0d039c4f899fa75b28d556d40516b9f7a61"
lazy = true

    [[View5D-jar.download]]
    url = "https://github.com/fiji/View5D/releases/download/2.3.1-jar/View5D_-2.3.1.jar.tar.gz"
    sha256 = "6ea67812f2438601bde1c3e72576ac616a0d29db460713c25e8d92610c987d5f"

