# cd("C:\\Users\\pi96doc\\Documents\\Programming\\Java\\View5D")
# using Pkg; Pkg.activate("."); using TestEnv; TestEnv.activate();
# ]add Tar, Inflate, SHA
# using Tar, Inflate, SHA

# V = 2; VV = 5; VVV = 5; Suffix = "-SNAPSHOT2";
# include("src\\get_artifact_info.jl")
# replace the code below with the printout
#
# remember to change the version number in the View5D.jl Project.toml file!
# Note that the Julia Version does not agree to the version of the Java View5D.
# for a full release: update the version number in Project.toml and comment "@JuliaRegistrator register"
# For reference the lines to generate the hashes below
# println("git-tree-sha1 = \"", Tar.tree_hash(IOBuffer(inflate_gzip(filename))),"\"")
# println("sha256 = \"", bytes2hex(open(sha256, filename)), "\"")
# https://github.com/bionanoimaging/View5D/releases/download/View5D_v2.5.5/View5D_-2.5.5-SNAPSHOT-jar.tar.gz

[View5D-jar]
git-tree-sha1 = "03165924bebed3b19e96530c40bdda55852ac8b7"
lazy = true

    [[View5D-jar.download]]
    url = "https://github.com/bionanoimaging/View5D/releases/download/View5D_v2.5.5/View5D_-2.5.5-SNAPSHOT2-jar.tar.gz"
    sha256 = "7fb7b386c7731b9c4b9267468ecfe23945fe1b81141a72bc84dd7ae0eb966121"
